ALTER TABLE t_bets MODIFY COLUMN bets_gold DECIMAL(19,8);
ALTER TABLE t_bets MODIFY COLUMN odds DECIMAL(7,2);

ALTER TABLE t_promoter MODIFY COLUMN bottom_gold DECIMAL(19,8);
ALTER TABLE t_promoter MODIFY COLUMN remain_gold DECIMAL(19,8);
ALTER TABLE t_promoter MODIFY COLUMN back_gold DECIMAL(19,8);
ALTER TABLE t_promoter MODIFY COLUMN odds DECIMAL(7,2);

ALTER TABLE t_token MODIFY COLUMN token DECIMAL(19,8);

ALTER TABLE t_token_history MODIFY COLUMN token DECIMAL(19,8);