# Configure development environment
server:
  port: 12020
  servlet:
    context-path:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

  
# Remove spring icon
spring.mvc.favicon.enabled: false

# Spring configuration
spring:
  profiles:
    active: dev
  application:
    name: bn-news
  session.store-type: none 
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  datasource:
    name: bn_news
    host: 127.0.0.1
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:3306/bn_news?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetim: 1200000
      connection-test-query: SELECT 1
  main:
    #    设置为true后，因为FeignClientSpecification的原因，FeignClient注解的configuration参数会被覆盖
    allow-bean-definition-overriding: true
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

  metrics:
    servo:
      enabled: false
  cloud:
    loadbalancer:
      retry:
        enabled: true
cors.allow.orgin: ${CORS_ALLOW_ORIGIN:*}
  
# Logging configuration
logging:
  config: classpath:logback-spring.xml

inner.server.host: 127.0.0.1
    
eureka:
  registry:
    port: 12060
  instance:
    hostname: 127.0.0.1
    status-page-url: http://${inner.server.host}:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone:  http://${eureka.instance.hostname}:${eureka.registry.port}/eureka/

btc:
  cmc:
    apiHost: https://pro-api.coinmarketcap.com
    apiKey: 08baa11d-fa13-46bb-8ccc-ae58fca4b6e8
    symbol: BTC,ETH,LTC,EOS
    exp: 0 0 0/1 * * ?
    marketInfo: 0 0/5 * * * ?

beetlsql:
  basePackage: io.bitnews.news.dao

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      timeout:
        enabled: false

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 3
  MaxAutoRetries: 3

feign:
  hystrix:
    enabled: true

