ALTER TABLE `t_coin_market` ADD COLUMN `market_cap` DECIMAL(19,2) NOT NULL DEFAULT '0' COMMENT '市场总量，单位亿USDT' AFTER `price`;
ALTER TABLE t_coin_market MODIFY COLUMN update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

